version: '3.2'
services:
  app:
    build: .
    ports:
      - 43000:3000
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=whatever
    volumes:
      - bundle:/bundle:cached
      - .:/ripper:cached
      - node-modules:/ripper/node_modules:cached
volumes:
  bundle:
  node-modules:
